[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npx pnpm@9.15.0 install --frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm@9.15.0 run build"]

[start]
cmd = "npx pnpm@9.15.0 run start"
