[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npx pnpm@9.15.0 install --no-frozen-lockfile --prod false"]

[phases.build]
cmds = ["npx pnpm@9.15.0 run build"]

[start]
cmd = "npx pnpm@9.15.0 --filter api run prisma:migrate:prod && node dist/main"